### ISSUE TITLE
I can get a .tk domain for this (it would reference GitPages)

### ISSUE THREAD

**Issue by card100** [Bloxport/bloxport.github.io#1]
I suggest making a `.tk` domain for this project.

**Comment by C0deAMet** [comment]
do you mean get a site domain. If yes then go for it and link me the domain link below

**Comment by theonlygusti** [comment]
It would be a pain though, as it would have to be renewed every 12 months.

Also, `.tk` isn't as "respected" (idk the better word, trusted?) as `.github.io`, so what would be the point?

**Comment by C0deAMet** [comment]
ok, good point
